// Criar usuário
POST  http://localhost:5000/usuarios
Content-Type: application/json

{
    "nome": "Nuguia",
    "email": "nuguia@gmail.com",
    "senha": "123456789",
    "confSenha": "123456789",
    "cargo": "admin"
}

###
// Trazer todos usuários
GET http://localhost:5000/usuarios
Content-Type: application/json

###
// Trazer usuário por ID
GET http://localhost:5000/usuarios/899bdde3-29a2-47c4-a4af-45eda2c4c623
Content-Type: application/json

###
// Editar usuário
PATCH http://localhost:5000/usuarios/899bdde3-29a2-47c4-a4af-45eda2c4c623
Content-Type: application/json

{
    "nome": "Johnathan Amorim",
    "email": "leccorside@gmail.com",
    "senha": "john020469",
    "confSenha": "john020469",
    "cargo": "admin"
}

###
// Deletar usuário
DELETE http://localhost:5000/usuarios/d2da18f5-ef8a-4fb3-a501-4560b25cebad
Content-Type: application/json

###
// Login
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "leccorside@gmail.com",
    "senha": "123"
}

###
// Painel
GET  http://localhost:5000/me
Content-Type: application/json

###
// Sair
DELETE  http://localhost:5000/logout
Content-Type: application/json